### ISSUE TITLE
[Feature]: Time

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/tasktrackr#1]
### So, what is it about?

In the addTask(string) function add another feature to store the time at which that particular task is created along with the task name.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jagpreet153** [comment]
@shobhit15082003 Could you please assign this task to me

**Comment by shobhit15082003** [comment]
## Assigned
You are supposed to submit a PR by 11:59 AM till 26.03.24.
(25.03.24 because of Holi)

**Comment by Shreyanshi210205** [comment]
@shobhit15082003 can you please assign this task to me.

**Comment by shobhit15082003** [comment]
## Assigned
You are supposed to raise a PR by 11:50 AM tommorow.

**Comment by SahilMorwal** [comment]
@shobhit15082003 can you assign me this task ?
