### ISSUE TITLE
[Feature]: Search task by Id

### ISSUE THREAD

**Issue by Jagpreet153** [OPCODE-Open-Spring-Fest/tasktrackr#19]
### So, what is it about?

Adding a feature to search a task on the basis of id

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jagpreet153** [comment]
@shobhit15082003 Assign this task to me please

**Comment by shobhit15082003** [comment]
## Assigned
You are supposed to raise a PR by 11:50 AM till 28.03.24
