### ISSUE TITLE
[Feature]: Display

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/tasktrackr#2]
### So, what is it about?

 Create a function to display the entered task.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jagpreet153** [comment]
@shobhit15082003 please assign this task to me

**Comment by shobhit15082003** [comment]
## Assigned

You are supposed to raise a PR by 11:50 AM tommorow i.e. by 25.03.24

**Comment by shobhit15082003** [comment]
## Assigned

You are supposed to raise a PR by 11:50 AM tommorow i.e. by 25.03.24
