### ISSUE TITLE
[Feature]: Update

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/tasktrackr#3]
### So, what is it about?

Create a function to update the current task.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sharvil-lade** [comment]
@shobhit15082003 please assign this task to me.

**Comment by shobhit15082003** [comment]
## Assigned
You are supposed to submit a pr by 11:59 AM tomorrow i.e. by 25.03.24
