### ISSUE TITLE
[Feature]: Sections

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/tasktrackr#5]
### So, what is it about?

Create two sections, one completed and another incomplete section and also create a function to display them.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sharvil-lade** [comment]
@shobhit15082003 please assign this task to me.

**Comment by shobhit15082003** [comment]
## Assigned
You are supposed to raise a pr till 11:50 AM till 28.03.24
