### ISSUE TITLE
[Feature]: Delete Everything

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/tasktrackr#6]
### So, what is it about?

Create an option to delete everything (i.e. delete everything from complete to incomplete section ) which means the entire data i.e. to destroy the entire contract.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sharvil-lade** [comment]
@shobhit15082003 please assign this task to me

**Comment by shobhit15082003** [comment]
## Assigned
You are supposed to raise a PR by 11:59 AM till 26.03.24.
(25.03.24 is excluded because of Holi)

**Comment by shobhit15082003** [comment]
@sharvil-lade delete everything ka ek alag sai pr yha phir sai raise karna
